pipeline {
    agent any

    stages {
        stage('Preview') {
            steps {
                sh "echo test"
            }
        }

        stage('Confirm') {
            steps {
                timeout(time: 30, unit: "MINUTES") {
                    input message: "Confirm rollback?", ok: "Yes"
                }
            }
        }

        stage('Rollback') {
            steps {
                sh "echo test"
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}
